/* Versioned local backups. Only explicitly listed application data is transferred. */
(function(root){'use strict';
const KEYS=['baby','favorites','logs','mamaTodayV1','mamaSleepV3History','mama-znaet-feeding-v3','mamaZnaetComplementaryFoods','mamaDevelopmentV4','developmentV2Checks','mamaExamsV1','mamaPlansV1','mamaGrowthCalendarV1','sleepV2Analyzer','feedingV2Analyzer'];
const JOURNAL='mamaBackupRollbackV1',META='mamaBackupMetaV1',LIMIT=8*1024*1024;
const object=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
function snapshot(storage){return Object.fromEntries(KEYS.map(k=>[k,storage.getItem(k)]));}
function apply(storage,data){for(const k of KEYS){if(data[k]===null)storage.removeItem(k);else storage.setItem(k,data[k]);}}
function rawValid(data){return object(data)&&Object.keys(data).length===KEYS.length&&KEYS.every(k=>Object.hasOwn(data,k)&&(data[k]===null||typeof data[k]==='string'));}
function validateValue(k,v){const arrays=['favorites','logs','mamaSleepV3History','mamaZnaetComplementaryFoods'];if(v===null){if(k==='baby'||k==='feedingV2Analyzer')return;throw Error('Некорректный раздел: '+k);}if(arrays.includes(k)){if(!Array.isArray(v)||v.length>10000)throw Error('Повреждён список: '+k);if(v.some(x=>!object(x)))throw Error('Повреждена запись: '+k);}else if(!object(v))throw Error('Повреждены настройки: '+k);
if(k==='baby'&&((v.birth!==undefined&&typeof v.birth!=='string')||(v.name!==undefined&&typeof v.name!=='string')))throw Error('Повреждён профиль.');
if(k==='favorites'&&v.some(x=>typeof x.id!=='string'||typeof x.title!=='string'||x.route!==undefined&&!object(x.route)))throw Error('Повреждены закладки.');
if(k==='mamaSleepV3History'&&v.some(x=>typeof x.date!=='string'||!Array.isArray(x.naps)||x.naps.some(n=>!object(n))))throw Error('Повреждён дневник сна.');
if(k==='mamaExamsV1'&&!object(v.visits))throw Error('Повреждены отметки осмотров.');
if(k==='mama-znaet-feeding-v3'&&(v.known!==undefined&&!Array.isArray(v.known)||v.repeats!==undefined&&!object(v.repeats)))throw Error('Повреждены настройки прикорма.');
if(k==='mamaDevelopmentV4'&&(v.checks!==undefined&&!object(v.checks)||v.notes!==undefined&&!object(v.notes)))throw Error('Повреждены наблюдения.');
}
function walk(v,depth=0){if(depth>25)throw Error('Слишком сложная структура файла.');if(typeof v==='string'&&/<\s*[a-z!/?]/i.test(v))throw Error('Файл содержит HTML-разметку. Используйте исходную копию приложения.');if(v&&typeof v==='object'){for(const [k,x]of Object.entries(v)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Недопустимое поле файла.');walk(x,depth+1);}}}
function validate(data){if(!rawValid(data))throw Error('Состав копии не соответствует этой версии приложения.');for(const k of KEYS){if(data[k]===null)continue;let v;try{v=JSON.parse(data[k]);}catch{throw Error('Не читается раздел: '+k);}validateValue(k,v);walk(v);}return data;}
async function digest(text,cryptoApi){const result=await cryptoApi.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(result),b=>b.toString(16).padStart(2,'0')).join('');}
async function pack(data,cryptoApi,now=new Date().toISOString()){const payload={app:'mama-znaet',version:1,createdAt:now,data};const text=JSON.stringify({...payload,checksum:await digest(JSON.stringify(payload),cryptoApi)},null,2);if(new TextEncoder().encode(text).length>LIMIT)throw Error('Копия больше 8 МБ.');return text;}
async function unpack(text,cryptoApi){if(new TextEncoder().encode(text).length>LIMIT)throw Error('Файл больше 8 МБ.');let f;try{f=JSON.parse(text);}catch{throw Error('Не удалось прочитать JSON. Выберите файл копии «Мама знает».');}if(!object(f)||f.app!=='mama-znaet'||f.version!==1||typeof f.createdAt!=='string'||!Number.isFinite(Date.parse(f.createdAt)))throw Error('Это не поддерживаемая копия «Мама знает».');const payload={app:f.app,version:f.version,createdAt:f.createdAt,data:f.data};if(typeof f.checksum!=='string'||await digest(JSON.stringify(payload),cryptoApi)!==f.checksum)throw Error('Файл изменён или повреждён. Выберите исходную копию.');validate(f.data);return f;}
function recover(storage){const raw=storage.getItem(JOURNAL);if(!raw)return false;const j=JSON.parse(raw);if(j.pending){if(!rawValid(j.before))throw Error('Не удалось прочитать страховочную копию.');apply(storage,j.before);storage.setItem(JOURNAL,JSON.stringify({...j,pending:false}));return true;}return false;}
function restore(storage,data){validate(data);const before=snapshot(storage),j={pending:true,before,createdAt:new Date().toISOString()};storage.setItem(JOURNAL,JSON.stringify(j));try{apply(storage,data);storage.setItem(JOURNAL,JSON.stringify({...j,pending:false}));}catch(error){try{apply(storage,before);storage.setItem(JOURNAL,JSON.stringify({...j,pending:false}));}catch{throw Error('Восстановление прервано. Страховочная копия сохранена; освободите место и перезагрузите приложение.');}throw Error('Не удалось записать копию. Прежние данные возвращены. Возможно, в браузере недостаточно места.');}}
function summary(data){const read=k=>{try{return JSON.parse(data[k]);}catch{return null;}};const p=read('baby'),sleep=read('mamaSleepV3History'),f=read('favorites');return {name:p?.name||'Без имени',birth:p?.birth||'Не указана',sleep:Array.isArray(sleep)?sleep.length:0,favorites:Array.isArray(f)?f.length:0,sections:KEYS.filter(k=>data[k]!==null).length};}
const api={KEYS,JOURNAL,META,LIMIT,snapshot,pack,unpack,restore,recover,summary,validate};if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(root?.document){root.MamaBackup=api;try{api.recovered=recover(root.localStorage);}catch(e){api.bootError=e.message;root.addEventListener('load',()=>{const panel=document.createElement('div');panel.style='position:fixed;inset:0;background:#fff9f7;z-index:2147483647;padding:40px;font:18px sans-serif';panel.textContent='Не удалось завершить возврат данных после прерванного восстановления. Страховочная копия остаётся в браузере. Освободите место на устройстве и перезагрузите страницу. Не очищайте данные приложения.';const button=document.createElement('button');button.textContent='Повторить после освобождения места';button.onclick=()=>location.reload();panel.append(button);document.body.append(panel);});}}
})(typeof window!=='undefined'?window:null);
