(function(){'use strict';const B=window.MamaBackup,root=document.getElementById('screen');let candidate=null,reading=0,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>Number.isFinite(Date.parse(s))?new Date(s).toLocaleString('ru-RU'):'Ещё не создавали';
function message(text){const el=root.querySelector('#backup-status');if(el)el.textContent=text;}
function info(s){return `<dl class="backup-summary"><dt>Профиль</dt><dd>${esc(s.name)}</dd><dt>Дата рождения</dt><dd>${esc(s.birth)}</dd><dt>Дней в дневнике сна</dt><dd>${s.sleep}</dd><dt>Закладок</dt><dd>${s.favorites}</dd><dt>Разделов с данными</dt><dd>${s.sections}</dd></dl>`;}
function meta(){try{return JSON.parse(localStorage.getItem(B.META)||'{}');}catch{return {};}}
async function download(data,prefix='mama-znaet-backup'){const text=await B.pack(data,crypto),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=prefix+'-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);return text;}
function screen(){candidate=null;reading++;closeModal();let rollback=false;try{rollback=!!localStorage.getItem(B.JOURNAL);}catch{}root.innerHTML=`<main class="mz-today backup-page"><button class="mz-link" data-mz="more">← Ещё</button><span class="mz-eyebrow">ВАШИ ЗАПИСИ С ВАМИ</span><h1 tabindex="-1">Копия моих данных</h1><p>Сохраните файл на телефон. Он поможет вернуть записи после очистки браузера или перенести их на другое устройство.</p><section class="mz-white"><h2>1. Сохранить копию</h2><p>В файл войдут профиль, дневники и заметки, избранное, прикорм и трекер продуктов, наблюдения за развитием, осмотры, прививки и настройки.</p><button type="button" class="mz-primary" id="backup-export">Скачать копию .json</button><p id="backup-date">Последняя подготовленная копия: ${esc(date(meta().exportedAt))}.</p><p class="mz-note">Проверьте, что файл появился в «Файлах» или «Загрузках». Если открыли приложение внутри Telegram и скачивание не работает, попробуйте его обычную веб-версию в браузере. Копию нужно создавать в том браузере, где находятся ваши записи.</p></section><section class="mz-white"><h2>2. Восстановить из копии</h2><p>Сначала покажем содержимое. Затем вы решите, заменять ли текущие записи. Данные не объединяются: всё будет как в выбранной копии, в том числе пустые разделы.</p><label for="backup-file">Выберите файл копии .json</label><input id="backup-file" type="file" accept=".json,application/json"><div id="backup-preview"></div></section>${rollback?'<section class="mz-white"><h2>Вернуть данные до последнего восстановления</h2><p>Страховочная копия хранится только в этом браузере. Она тоже исчезнет при очистке его данных.</p><button type="button" id="backup-undo" class="mz-secondary">Посмотреть страховочную копию</button></section>':''}<p id="backup-status" role="status"></p><p class="mz-footnote">Файл содержит личные записи о вас и малыше и не защищён паролем. Храните его у себя. Автоматической синхронизации пока нет; файл обрабатывается на устройстве.</p></main>`;
root.querySelector('#backup-export').onclick=async()=>{if(busy)return;busy=true;try{await download(B.snapshot(localStorage));const time=new Date().toISOString();try{localStorage.setItem(B.META,JSON.stringify({...meta(),exportedAt:time}));}catch{}root.querySelector('#backup-date').textContent='Последняя подготовленная копия: '+date(time)+'.';message('Файл подготовлен к скачиванию. Проверьте его сохранение в «Файлах» или «Загрузках».');}catch{message('Не удалось подготовить копию. Попробуйте снова в этом браузере; данные не изменены.');}finally{busy=false;}};
root.querySelector('#backup-file').onchange=async e=>{const token=++reading;candidate=null;root.querySelector('#backup-preview').innerHTML='';const file=e.target.files[0];if(!file)return;message('Проверяем файл…');try{if(file.size>B.LIMIT)throw Error('Файл больше 8 МБ.');const c=await B.unpack(await file.text(),crypto);if(token!==reading)return;candidate=c;preview();message('Файл проверен. Текущие данные ещё не изменены.');}catch(error){if(token===reading)message(error.message);}};
root.querySelector('#backup-undo')?.addEventListener('click',()=>{try{const j=JSON.parse(localStorage.getItem(B.JOURNAL));B.validate(j.before);candidate={data:j.before,createdAt:j.createdAt};preview();message('Это данные до последней попытки восстановления. Проверьте их перед возвратом.');}catch{message('Не удалось прочитать страховочную копию. Текущие данные не изменены.');}});window.scrollTo(0,0);root.querySelector('h1').focus();}
function preview(){const s=B.summary(candidate.data),current=B.summary(B.snapshot(localStorage));root.querySelector('#backup-preview').innerHTML=`<div class="backup-preview"><h3>В выбранной копии</h3><p>Создана: ${esc(date(candidate.createdAt))}</p>${info(s)}<details><summary>Что сейчас в приложении</summary>${info(current)}</details><button type="button" id="backup-save-before" class="mz-secondary">Сначала скачать текущие данные</button><label class="backup-consent"><input type="checkbox" id="backup-confirm">Понимаю: текущие данные будут заменены содержимым этой копии.</label><button type="button" id="backup-restore" class="mz-primary" disabled>Восстановить и перезапустить</button><button type="button" id="backup-cancel" class="mz-link">Отмена</button></div>`;root.querySelector('#backup-confirm').onchange=e=>root.querySelector('#backup-restore').disabled=!e.target.checked;root.querySelector('#backup-save-before').onclick=async()=>{try{await download(B.snapshot(localStorage),'mama-znaet-before-restore');message('Текущие данные подготовлены к скачиванию. Проверьте сохранение файла.');}catch{message('Не удалось скачать текущие данные.');}};root.querySelector('#backup-cancel').onclick=()=>{candidate=null;reading++;root.querySelector('#backup-file').value='';root.querySelector('#backup-preview').innerHTML='';message('Восстановление отменено. Данные не изменены.');};root.querySelector('#backup-restore').onclick=()=>{if(!candidate||busy||!root.querySelector('#backup-confirm').checked)return;busy=true;try{B.restore(localStorage,candidate.data);location.reload();}catch(e){message(e.message);busy=false;}};}
window.openMamaBackup=screen;document.addEventListener('click',e=>{if(e.target.closest('[data-backup-open]'))screen();});
})();
