(function(){
'use strict';
const D=MAMA_DEV4,KEY='mamaDevelopmentV4';
const tabs=[['skills','Умения'],['senses','Зрение и слух'],['games','Игры'],['tips','Лайфхаки'],['notes','Мои наблюдения']];
let month=0,active='skills';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const age=i=>i===0?'0–1 месяц':i<4?`${i}–${i+1} месяца`:`${i}–${i+1} месяцев`;
const deadline=n=>n===12?'К 12 месяцам':`К ${n} месяцам`;
function read(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return s&&typeof s==='object'&&!Array.isArray(s)?s:{};}catch{return {};}}
function save(s){try{localStorage.setItem(KEY,JSON.stringify(s));return true;}catch{return false;}}
function profileMonth(){return window.MamaProfile.months(window.MamaProfile.birth());}

function sources(){const ids=[...new Set(D.months[month].skills.map(k=>String(D.skills[k][3])))];return `<details class="dv4-details dv4-sources"><summary>Источники и как читать ориентиры</summary><div class="dv4-detail-body"><p>В карточках указан возраст, к которому навык наблюдают у большинства детей, а не точный месяц его появления. Часть навыков может быть ещё впереди. Если возраст уже наступил, а навык не появился, обсудите это с педиатром.</p><p>Для малыша, родившегося раньше срока, ориентиры обычно сопоставляют со скорректированным возрастом: из возраста после рождения вычитают число недель, недостающих до 40 недель беременности. Подходящий возраст для наблюдений уточните у врача и выберите вручную выше.</p><p>Содержание сверено с источниками 5 октября 2026 года. Ссылки ведут на материалы на английском. Игры — бытовые сценарии, а не лечебная гимнастика.</p>${[...ids,'vision','eyes','hearing','play','move','preterm'].map(k=>`<p><a href="${D.sources[k][1]}" target="_blank" rel="noopener noreferrer">${esc(D.sources[k][0])} ↗</a></p>`).join('')}</div></details>`;}
function help(){return `<details class="dv4-details dv4-help"><summary>Когда стоит обсудить развитие с врачом</summary><div class="dv4-detail-body"><p>Не ждите следующего месяца, если ребёнок потерял уже освоенный навык, почти не использует одну сторону тела, не реагирует на обычные звуки или вас тревожит его зрение. Отсутствие возрастного ориентира тоже повод для разговора с педиатром.</p><p>Запишите, что именно заметили и когда. Короткое видео обычного поведения можно показать на приёме. Не проверяйте слух громкими хлопками у уха и не повторяйте движение через плач.</p><p>Если малыш внезапно стал необычно вялым, его трудно разбудить или ему трудно дышать — нужна срочная помощь, а не занятие.</p></div></details>`;}
function skillPanel(){const m=D.months[month];return `<h2 tabindex="-1">Что малыш уже умеет и чему учится</h2><p class="dv4-muted">Наблюдайте в обычной жизни. Возраст на карточке — ориентир, а не задание на сегодня.</p><div class="dv4-skills">${m.skills.map(k=>{const s=D.skills[k];return `<details class="dv4-details dv4-skill"><summary><span class="dv4-eyebrow">${s[1]} · ${deadline(s[3])}</span><span class="dv4-skill-title">${esc(s[0])}</span><span class="dv4-open-hint">Как это выглядит в жизни</span></summary><div class="dv4-detail-body"><p>${esc(s[2])}</p><button type="button" data-dv-tab="notes">Отметить в наблюдениях →</button></div></details>`;}).join('')}</div><aside class="dv4-try"><span class="dv4-eyebrow">ПОПРОБУЙТЕ ВМЕСТЕ</span><h3>${esc(D.games[m.games[0]].title)}</h3><p>${esc(D.games[m.games[0]].about)}. Всё нужное и пошаговый сценарий — внутри.</p><button type="button" data-dv-game="${m.games[0]}">Открыть игру →</button></aside>`;}
function sensePanel(){const s=D.senses[D.months[month].sense];return `<h2 tabindex="-1">Как малыш видит и слышит</h2><p class="dv4-muted">${s.title}. Зрение и слух развиваются постепенно, без переключения в день нового месяца.</p><div class="dv4-sense-grid"><article class="dv4-card"><span class="dv4-symbol" aria-hidden="true">◉</span><h3>Что видит</h3><p>${esc(s.see)}</p></article><article class="dv4-card"><span class="dv4-symbol" aria-hidden="true">♫</span><h3>Что слышит и понимает</h3><p>${esc(s.hear)}</p></article></div><aside class="dv4-try"><h3>Как общаться сейчас</h3><p>${esc(s.try)}</p></aside><details class="dv4-details"><summary>Как заметить, что впечатлений уже достаточно</summary><div class="dv4-detail-body"><p>Если малыш отворачивается, зевает, хнычет или перестаёт интересоваться, уберите игрушку и сделайте паузу. Не нужно усиливать свет, звук или темп, чтобы вернуть внимание.</p><p>Одна реакция не проверяет зрение или слух. Если сомнения повторяются, расскажите об этом педиатру.</p></div></details>`;}
function gameCard(k,index){const g=D.games[k];return `<details class="dv4-details dv4-game" id="dv4-game-${k}"><summary><span class="dv4-eyebrow">ИГРА ${index+1} · ВМЕСТЕ СО ВЗРОСЛЫМ</span><span class="dv4-skill-title">${esc(g.title)}</span><span class="dv4-open-hint">${esc(g.about)} · открыть шаги</span></summary><div class="dv4-detail-body"><h3>Что понадобится</h3><p>${esc(g.need)}</p><h3>Как играть</h3><ol>${g.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>Что можно заметить</h3><p>${esc(g.notice)}</p><h3>Если пока трудно</h3><p>${esc(g.easier)}</p><p class="dv4-safety"><strong>Безопасность.</strong> ${esc(g.safe)}</p></div></details>`;}
function gamesPanel(){return `<h2 tabindex="-1">Во что поиграть сегодня</h2><p>Выберите одну игру по настроению. Закончить можно через несколько секунд — интерес малыша важнее длительности.</p><div class="dv4-game-list">${D.months[month].games.map(gameCard).join('')}</div><p class="dv4-muted">Отворачивается, устал или плачет — остановитесь. Любимую игру можно повторять; выполнять весь список не требуется.</p>`;}
function tipsPanel(){return `<h2 tabindex="-1">Маленькие хитрости для мамы</h2><p class="dv4-muted">Чтобы игры легко помещались в обычный день.</p><div class="dv4-tip-list">${D.months[month].tips.map(([h,t],i)=>`<article class="dv4-card dv4-tip"><span class="dv4-tip-number" aria-hidden="true">0${i+1}</span><div><h3>${esc(h)}</h3><p>${esc(t)}</p></div></article>`).join('')}</div><details class="dv4-details"><summary>Если сегодня совсем нет сил</summary><div class="dv4-detail-body"><p>Выберите одно простое действие: улыбнитесь во время переодевания, назовите игрушку или ответьте на звук. Не нужно устраивать отдельный урок или покупать развивающий набор.</p><p>Если не получилось поиграть — не надо завтра «отрабатывать» пропущенное.</p></div></details>`;}
function legacy(){
 let old;try{old=JSON.parse(localStorage.getItem('developmentV2Checks')||'{}');}catch{return '';}
 if(!old||typeof old!=='object'||typeof developmentV2==='undefined')return '';
 const rows=[];for(let i=0;i<12;i++){const items=(developmentV2[i]?.checklist||[]).filter((_,j)=>old[i]?.[j]===true);if(items.length)rows.push(`<h4>${age(i)}</h4><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`);}
 return rows.length?`<details class="dv4-details"><summary>Мои отметки из прежнего раздела</summary><div class="dv4-detail-body"><p>Сохранены с прежними формулировками. Они не перенесены на другие навыки автоматически.</p>${rows.join('')}</div></details>`:'';
}
function notesPanel(){const s=read();return `<h2 tabindex="-1">Что я замечаю у малыша</h2><p>Отметьте только то, что уже видели. Пустая отметка значит «пока не отмечено», а не «ребёнок не умеет». Здесь нет баллов и рейтинга развития.</p><div class="dv4-checks">${D.months[month].skills.map(k=>`<label class="dv4-check"><input type="checkbox" data-dv-check="${k}" ${s.checks?.[k]===true?'checked':''}><span>${esc(D.skills[k][0])}<small>${deadline(D.skills[k][3])} · ориентир</small></span></label>`).join('')}</div><label class="dv4-note-label" for="dv4-note">Моя заметка за ${age(month)}</label><p class="dv4-muted" id="dv4-note-hint">Например: «Сегодня потянулся к кольцу сам» или «Хочу спросить врача про поворот головы».</p><textarea id="dv4-note" aria-describedby="dv4-note-hint" maxlength="3000" placeholder="Что нового вы заметили?">${esc(typeof s.notes?.[month]==='string'?s.notes[month]:'')}</textarea><button type="button" data-dv-save>Сохранить заметку</button><p class="dv4-muted">Галочки сохраняются сразу. Заметка — по кнопке и при переходе к другой теме или месяцу. Данные остаются в этом браузере; при очистке его данных они исчезнут.</p>${legacy()}`;}
function panel(){return ({skills:skillPanel,senses:sensePanel,games:gamesPanel,tips:tipsPanel,notes:notesPanel})[active]();}
function render(focus=false){
 const m=D.months[month],p=profileMonth();
 const root=document.getElementById('screen');
 root.innerHTML=`<div class="dv4"><button class="dv4-back" type="button" data-dv-home>← На главную</button><header class="dv4-header"><span class="dv4-eyebrow">РАСТЁМ И ИГРАЕМ</span><h1>Мир глазами малыша</h1><p>Понятно о развитии. Интересно быть вместе.</p></header><section class="dv4-agebar" aria-label="Выбор возраста"><label for="dv4-age">Возраст малыша</label><div class="dv4-agecontrols"><button type="button" data-dv-step="-1" aria-label="Предыдущий месяц" ${month===0?'disabled':''}>←</button><select id="dv4-age">${D.months.map((m,i)=>`<option value="${i}" ${i===month?'selected':''}>${age(i)}</option>`).join('')}</select><button type="button" data-dv-step="1" aria-label="Следующий месяц" ${month===11?'disabled':''}>→</button></div><p class="dv4-muted">${p===null?'Выберите месяц вручную. Дату рождения можно указать в профиле малыша.':p>11?'Малышу уже год или больше. Здесь показан завершающий этап первого года.':month===p?'Выбран возраст по дате рождения в профиле.':'Вы смотрите другой возраст.'} ${p!==null&&p<=11&&month!==p?'<button type="button" class="dv4-link" data-dv-current>К возрасту моего малыша</button>':''}</p></section><section class="dv4-month"><span class="dv4-month-icon" aria-hidden="true">${m.icon}</span><div><span class="dv4-eyebrow">${age(month)}</span><h2>${esc(m.title)}</h2><p>${esc(m.intro)}</p></div></section><nav class="dv4-tabs" aria-label="Темы развития">${tabs.map(([k,t])=>`<button type="button" data-dv-tab="${k}" aria-pressed="${active===k}" aria-controls="dv4-panel">${t}</button>`).join('')}</nav><section id="dv4-panel" class="dv4-panel">${panel()}</section><p id="dv4-status" class="dv4-status" role="status" aria-live="polite"></p>${help()}${sources()}</div>`;
 window.MamaFavorites?.offer({kind:'development',key:String(month),tab:active,title:age(month)+' · '+tabs.find(t=>t[0]===active)[1]},root);
 if(focus)root.querySelector('#dv4-panel h2')?.focus({preventScroll:true});
}
function captureNote(){if(active!=='notes')return true;const el=document.getElementById('dv4-note');if(!el)return true;const s=read(),prev=typeof s.notes?.[month]==='string'?s.notes[month]:'';if(el.value===prev)return true;if(!s.notes||typeof s.notes!=='object')s.notes={};s.notes[month]=el.value;if(save(s))return true;status('Не удалось сохранить заметку. Скопируйте её перед выходом; можно попробовать ещё раз.');return false;}
function status(s){const el=document.getElementById('dv4-status');if(el)el.textContent=s;}
function open(index){if(typeof closeModal==='function')closeModal();const i=Number(index);month=Number.isInteger(i)&&i>=0&&i<=11?i:Math.min(11,profileMonth()??0);active='skills';render();window.scrollTo(0,0);}
window.openDevelopmentBookmark=(index,tab)=>{open(index);if(tabs.some(t=>t[0]===tab))active=tab;render();};
window.openDevelopmentV2=()=>open();
window.openDevelopmentV2Age=index=>open(index);
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-dv-tab],[data-dv-step],[data-dv-current],[data-dv-home],[data-dv-game],[data-dv-save]');if(!b)return;
 if(b.hasAttribute('data-dv-save')){if(captureNote())status('Заметка сохранена в этом браузере.');return;}
 if(!captureNote())return;
 if(b.hasAttribute('data-dv-home')){location.reload();return;}
 if(b.hasAttribute('data-dv-tab')){if(tabs.some(t=>t[0]===b.dataset.dvTab))active=b.dataset.dvTab;render(true);}
 else if(b.hasAttribute('data-dv-step')){month=Math.max(0,Math.min(11,month+Number(b.dataset.dvStep)));render(true);}
 else if(b.hasAttribute('data-dv-current')){month=Math.min(11,profileMonth()??0);render(true);}
 else if(b.hasAttribute('data-dv-game')){const k=b.dataset.dvGame;if(!D.months[month].games.includes(k))return;active='games';render(true);const g=document.getElementById('dv4-game-'+k);g.open=true;g.scrollIntoView({behavior:'smooth',block:'start'});}
});
document.addEventListener('change',e=>{
 if(e.target.id==='dv4-age'){if(!captureNote()){e.target.value=String(month);return;}const v=Number(e.target.value);if(Number.isInteger(v)&&v>=0&&v<=11){month=v;render(true);}}
 if(e.target.matches('[data-dv-check]')){const k=e.target.dataset.dvCheck;if(!D.skills[k])return;const s=read();if(!s.checks||typeof s.checks!=='object')s.checks={};s.checks[k]=e.target.checked;if(save(s))status(e.target.checked?'Наблюдение сохранено.':'Отметка снята.');else{e.target.checked=!e.target.checked;status('Не удалось сохранить отметку в браузере. Попробуйте ещё раз.');}}
});
})();

