(function(){
'use strict';
const data=window.MAMA_EXAMS, key='mamaExamsV1';
let store={birth:'',profileBirth:'',visits:{}}, storageError=false, month=0, tab='plan';
try{const v=JSON.parse(localStorage.getItem(key)||'null');if(v&&typeof v==='object'&&v.visits&&typeof v.visits==='object'&&!Array.isArray(v.visits))store=v;}catch(e){storageError=true;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function parse(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return null;const d=new Date(s+'T12:00:00Z');return Number.isNaN(+d)||d.toISOString().slice(0,10)!==s?null:d;}
function valid(s){return !!parse(s)&&s<=today();}
function addMonths(s,m){const d=parse(s);if(!d)return null;const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+m);d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));return d.toISOString().slice(0,10);}
function age(s,now=today()){if(!parse(s)||s>now)return null;const d=parse(s),n=parse(now);let m=(n.getUTCFullYear()-d.getUTCFullYear())*12+n.getUTCMonth()-d.getUTCMonth();if(addMonths(s,m)>now)m--;return m;}
const fmt=s=>parse(s).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
const label=m=>m===0?'После рождения':m===1?'1 месяц':m<5?m+' месяца':m+' месяцев';
function profile(){return typeof baby!=='undefined'&&baby&&valid(baby.birth)?baby.birth:'';}
function birth(){const p=profile();if(p!==store.profileBirth)return p;return valid(store.birth)?store.birth:p;}
function save(){try{localStorage.setItem(key,JSON.stringify(store));storageError=false;return true;}catch(e){storageError=true;return false;}}
function checks(b=birth(),m=month){return store.visits[b]?.[m]||{};}
function ids(m){const s=data.stages[m];return s.doctors.concat(s.tests);}
function complete(b,m){return ids(m).every(k=>checks(b,m)[k]===true);}
function nearest(b=birth(),now=today()){const a=age(b,now);if(a===null||a>12)return null;for(let m=Math.max(0,a);m<=12;m++)if(!complete(b,m))return m;return null;}
function sources(){return '<details class="exam-card"><summary>Источники и актуальность</summary><p>Сверено 5 октября 2026 года. План первого года по приказу Минздрава России от 14.04.2025 № 211н, действующему с 1 сентября 2025 года.</p><p><a href="https://dgp110.mos.ru/links/profilaktika/profosmotr/" target="_blank" rel="noopener noreferrer">Перечень обследований — государственная детская поликлиника № 110 ↗</a></p><p><a href="https://legalacts.ru/doc/prikaz-minzdrava-rossii-ot-14042025-n-211n-ob-utverzhdenii/" target="_blank" rel="noopener noreferrer">Полный текст приказа № 211н ↗</a></p><p><a href="https://dgp110.mos.ru/links/prepare/314/457/" target="_blank" rel="noopener noreferrer">Подготовка новорождённого к скрининговому УЗИ ↗</a></p></details>';}
function card(k){const x=data.items[k],b=birth();return '<article class="exam-item"><div class="exam-item-top"><label><input type="checkbox" data-exam-check="'+k+'" '+(checks()[k]===true?'checked ':'')+(!b?'disabled ':'')+'aria-label="Пройдено: '+esc(x[0])+'"><span>'+x[0]+'</span></label></div><p class="exam-muted">'+x[1]+'</p><details><summary>Что будет на приёме и как подготовиться</summary><p>'+x[2]+'</p><div class="exam-note"><b>Перед посещением</b><p>'+x[3]+'</p></div></details></article>';}
function plan(){const b=birth(),s=data.stages[month],n=nearest(),a=age(b),total=ids(month).length,done=ids(month).filter(k=>checks()[k]===true).length;
return '<section class="exam-card"><label for="examMonth">Посмотреть возраст</label><select id="examMonth">'+data.stages.map(s=>'<option value="'+s.month+'" '+(s.month===month?'selected':'')+'>'+label(s.month)+'</option>').join('')+'</select>'+(b?'<p class="exam-date">'+(month===0?'Дата рождения: ':'Возраст исполнится: ')+fmt(addMonths(b,month))+'</p>':'')+'<p class="exam-muted">Дата — возрастной ориентир, а не запись в поликлинику. Конкретный день согласуйте с врачом.</p>'+(n!==null&&n!==month?'<button class="exam-action" id="examNearest">Показать актуальный осмотр · '+label(n)+'</button>':'')+'</section>'+(a!==null&&a>12?'<aside class="exam-note">Здесь собран первый год жизни, включая осмотр в 12 месяцев. Следующий возрастной осмотр уточните у педиатра. Старые отметки остаются доступны.</aside>':'')+'<h2>'+label(month)+' · план осмотра</h2><p class="exam-muted">'+(b?'Вы отметили '+done+' из '+total+' пунктов. Отмечайте фактически пройденное; это ваши записи, не медицинское заключение.':'Добавьте дату рождения, чтобы сохранять отметки отдельно для малыша.')+'</p><h3>Врачи</h3>'+s.doctors.map(card).join('')+'<h3>Анализы и обследования</h3>'+(s.tests.length?s.tests.map(card).join(''):'<div class="exam-note">В этом возрасте в общем перечне нет дополнительных плановых анализов и исследований. Врач может назначить их по жалобам, истории ребёнка или результатам осмотра.</div>')+(month===1||month===12?'<p class="exam-muted">Исследования в рамках осмотра врача показаны отдельными пунктами, чтобы вы могли проверить их выполнение. Число пунктов не равно числу отдельных посещений.</p>':'')+(b?'<details class="exam-card"><summary>Что проверить после приёма</summary><p>Получили ли вы заключения и расшифровки? Понятно ли, что делать дальше и когда прийти снова? Если врач назначил дополнительное обследование, запишите его отдельно: оно не появится здесь автоматически.</p><p>Отметки сохраняются в этом браузере. При очистке данных или смене устройства они могут исчезнуть.</p></details>':'')+'<aside class="exam-note"><b>Если что-то пропустили</b><p>Сверьте прошлые месяцы с выписками и обсудите с педиатром, что нужно пройти сейчас. Приложение не считает прошлые осмотры выполненными автоматически и не назначает повторные исследования.</p></aside>';}
function preparation(){return '<h2>Собираемся без спешки</h2>'+[
['1. Начните с поликлиники','Скажите: «Ребёнку скоро исполнится … месяцев. Хотим пройти профилактический осмотр. Какие направления нужны и куда записываться?» Уточните, что можно пройти в один день, а что — отдельно.'],
['2. Подготовьте документы','Возьмите документы ребёнка и представителя, полис ОМС, выписку из роддома, результаты прошлых обследований и прививочный сертификат. Нужен ли бумажный оригинал конкретного документа, можно уточнить при записи.'],
['3. Соберите небольшую сумку','Пелёнка, подгузники, салфетки, сменная одежда, привычное питание и любимая игрушка. Удобнее одежда с кнопками: её проще снять для осмотра.'],
['4. Запишите три главных вопроса','Например: «Как меняется прибавка веса?», «Что обсудить по кормлению?», «Нужно ли показать это движение на видео?» Начните приём с самого важного.'],
['5. Подготовку уточняйте для каждого исследования','Назовите возраст ребёнка и спросите, можно ли кормить перед исследованием, как собрать материал и когда его доставить. Правила для взрослых не подходят грудничку. Не отменяйте лекарства и не устраивайте длительное голодание самостоятельно.'],
['6. После приёма соберите результаты','Сфотографируйте заключения и храните их в одной папке. Попросите объяснить непонятные слова и написать, что делать дальше. Отмечайте пункты в приложении после фактического прохождения.']
].map(x=>'<article class="exam-card"><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join('')+'<aside class="exam-note"><b>Лайфхак</b><p>Когда записываетесь сразу в несколько кабинетов, заложите время на кормление, переодевание и ожидание. План «всё за час» с малышом часто оказывается неудобным.</p></aside>';}
function faq(){return '<h2>Понятные ответы</h2>'+[
['Если малыш выглядит здоровым, зачем осмотр?','Профилактический осмотр проводят, чтобы оценить здоровье и развитие, заметить проблемы до выраженных жалоб и обсудить уход. Это отличается от обращения из-за болезни.'],
['Почему в некоторых месяцах только педиатр?','Так устроен общий возрастной перечень. Это не значит, что обследования запрещены: при необходимости педиатр направит к специалисту или на анализы независимо от месяца.'],
['Можно ли использовать недавние результаты?','Покажите их педиатру до повторной записи. По порядку у детей до двух лет могут учитываться внесённые в медицинские документы результаты давностью не более одного месяца. Какие результаты подходят для вашего осмотра, проверит врач.'],
['Это бесплатно?','Профилактические осмотры предусмотрены программой государственных гарантий, в том числе по ОМС. Уточните порядок направлений в прикреплённой поликлинике.'],
['А прививки входят в этот список?','Календарь прививок — отдельный раздел. Профилактический осмотр и вакцинация связаны, но не заменяют друг друга. Назначенный день вакцинации согласуйте с поликлиникой.'],
['Ребёнок родился раньше срока — что выбирать?','Укажите настоящую дату рождения. Для профилактического графика приложение считает календарный возраст. Недоношенному ребёнку могут понадобиться дополнительные осмотры и индивидуальные сроки — ориентируйтесь на выписку и план наблюдающего врача.'],
['Если ребёнок заболел перед плановым приёмом','Свяжитесь с поликлиникой и уточните маршрут обращения. Не откладывайте помощь до плановой даты. При затруднении дыхания, потере сознания или судорогах вызывайте экстренную помощь по 112.'],
['Почему ближайший осмотр ещё относится к текущему месяцу?','Приложение показывает осмотр для уже наступившего возраста, пока вы не отметили все его пункты. После этого покажет следующий. Прошлые месяцы остаются для проверки вручную; отметка не подтверждает заключение врача.']
].map(x=>'<details class="exam-card"><summary>'+x[0]+'</summary><p>'+x[1]+'</p></details>').join('')+'<button class="exam-action" id="examVaccines">Открыть календарь прививок →</button>'+sources();}
function render(){const root=document.getElementById('screen');if(!root)return;const b=birth();root.innerHTML='<main class="exam-page"><button class="exam-back" onclick="location.reload()">← На главную</button><header><div class="exam-eyebrow">МАМА ЗНАЕТ · ЗДОРОВЬЕ</div><h1>Профилактические осмотры</h1><p>К кому идти, что проверить и как подготовиться в первый год жизни.</p></header><section class="exam-card"><label for="examBirth">Дата рождения малыша</label><input id="examBirth" type="date" value="'+esc(b)+'" max="'+today()+'"><p class="exam-muted">Используем дату из профиля. Здесь можно выбрать другую для этого календаря — сам профиль не изменится.</p></section><p id="examStatus" role="status" class="exam-status">'+(storageError?'Не удалось сохранить или прочитать отметки в этом браузере. Проверьте доступ к хранилищу.':'')+'</p><nav class="exam-tabs" aria-label="Разделы осмотров">'+[['plan','План по возрасту'],['prepare','Подготовка'],['faq','Вопросы и источники']].map(x=>'<button data-exam-tab="'+x[0]+'" aria-pressed="'+(tab===x[0])+'">'+x[1]+'</button>').join('')+'</nav><section>'+ (tab==='plan'?plan():tab==='prepare'?preparation():faq())+'</section><footer>Ориентир по общему порядку РФ. При жалобах, хронических заболеваниях и индивидуальном наблюдении план может отличаться. Не ждите плановой даты, если ребёнку нужна помощь.</footer></main>';
root.querySelector('#examBirth').addEventListener('change',e=>{const v=e.target.value;if(v&&!valid(v)){e.target.setCustomValidity('Укажите существующую дату, не позже сегодняшней.');e.target.reportValidity();return;}store.birth=v;store.profileBirth=profile();save();month=nearest()??Math.min(12,Math.max(0,age(birth())||0));render();});
root.querySelectorAll('[data-exam-tab]').forEach(el=>el.addEventListener('click',()=>{tab=el.dataset.examTab;render();}));
root.querySelector('#examMonth')?.addEventListener('change',e=>{month=Number(e.target.value);render();});
root.querySelector('#examNearest')?.addEventListener('click',()=>{month=nearest()??month;render();});
root.querySelector('#examVaccines')?.addEventListener('click',()=>window.openVaccinationCalendar());
root.querySelectorAll('[data-exam-check]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.examCheck,b=birth();if(!valid(b))return;store.visits[b]??={};store.visits[b][month]??={};const prev=store.visits[b][month][k];store.visits[b][month][k]=el.checked;if(!save()){store.visits[b][month][k]=prev;el.checked=prev===true;document.getElementById('examStatus').textContent='Не удалось сохранить отметку. Она не изменена. Проверьте настройки браузера.';return;}const focus=k;render();root.querySelector('[data-exam-check="'+focus+'"]')?.focus();}));}
window.openPreventiveExams=function(){if(typeof closeModal==='function')closeModal();tab='plan';const b=birth();month=nearest(b)??Math.min(12,Math.max(0,age(b)||0));render();window.scrollTo(0,0);};
function home(){const el=document.getElementById('nextDoctor');if(!el)return;const item=el.closest('.next-item');if(item){item.onclick=window.openPreventiveExams;item.setAttribute('role','button');item.tabIndex=0;item.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();window.openPreventiveExams();}};}const b=birth(),m=nearest(b),text=document.getElementById('nextDoctorText');el.textContent=m===null?'Профилактические осмотры':(age(b)===m?'Актуально: ':'Далее: ')+label(m);if(text)text.textContent=m===null?(b?'План первого года, ваши отметки и подготовка':'Укажите дату рождения — покажем осмотр по возрасту'):(m===0?'Педиатр и проверка скринингов':fmt(addMonths(b,m))+' · '+data.stages[m].doctors.map(k=>data.items[k][0]).join(', '));}
if(typeof renderNextContent==='function'){const old=renderNextContent;renderNextContent=function(){old.apply(this,arguments);home();};}home();
if(typeof module!=='undefined'&&module.exports)module.exports={parse,addMonths,age,nearest,complete,ids,birth,home};
})();
