(function(){'use strict';
const KEY='favorites',root=document.getElementById('screen');let removed=null,toastTimer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={care:'Уход за малышом',postpartum:'После естественных родов',cesarean:'После кесарева сечения',breastfeeding:'Грудное вскармливание',development:'Развитие',motor:'Упражнения',guide:'Памятки по шагам',section:'Раздел',legacy:'Ранее сохранено'};
function read(){try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'):[];}catch{return [];}}
function write(rows){try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(raw))return false;localStorage.setItem(KEY,JSON.stringify(rows));if(typeof favoritesList!=='undefined')favoritesList=rows;return true;}catch{return false;}}
function identity(r){return ['v2',r.kind,r.key??'',r.tab??''].join(':');}
function status(message){let el=document.getElementById('fav-toast');if(!el){el=document.createElement('div');el.id='fav-toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),5000);}
function refresh(){const rows=read();document.querySelectorAll('[data-mz-bookmark]').forEach(b=>{const saved=rows.some(x=>x.id===b.dataset.id);b.textContent=saved?'♥ В избранном':'♡ Сохранить в избранное';b.setAttribute('aria-pressed',String(saved));});document.querySelectorAll('button[onclick*="toggleFavorite"]').forEach(b=>{const m=b.getAttribute('onclick').match(/toggleFavorite\(\s*['"]([^'"]+)['"]/);if(m)b.textContent=rows.some(x=>x.id===m[1])?'♥ В избранном':'♡ Сохранить в избранное';});}
function toggle(item){const rows=read(),exists=rows.some(x=>x.id===item.id);const next=exists?rows.filter(x=>x.id!==item.id):[...rows,item];if(!write(next)){status('Не удалось сохранить изменения. Проверьте настройки хранения данных в браузере.');return;}refresh();status(exists?'Убрано из избранного.':'Сохранено. Откройте «Ещё» → «Избранное», чтобы вернуться.');}
function offer(route,container=root){if(!container||!route.title)return;container.querySelectorAll('[data-mz-bookmark]').forEach(b=>b.remove());const heading=container.querySelector('h1,h2');if(!heading)return;const b=document.createElement('button');b.type='button';b.className='fav-save';b.dataset.mzBookmark='';b.dataset.id=identity(route);b.addEventListener('click',()=>toggle({id:identity(route),title:route.title,route:{kind:route.kind,key:route.key,tab:route.tab}}));heading.insertAdjacentElement('afterend',b);refresh();}
const sectionFns={care:'openCareV2',postpartum:'openPostpartumV2',cesarean:'openCesareanV2',breastfeeding:'openBreastfeedingV2',sleep:'openSleepV2',feeding:'openFeedingV2',health:'openHealthV2',complementary:'openComplementaryV2',calendar:'openComplementaryCalendar',vaccines:'openVaccinationCalendar',exams:'openPreventiveExams',growth:'openGrowthCalendar'};
function open(item){closeModal();const r=item.route;try{if(r){if(['care','postpartum','cesarean','breastfeeding'].includes(r.kind)){const fn=window.MamaFavoriteArticles?.[r.kind];if(typeof fn!=='function')throw new Error('Unavailable');fn(r.key);return;}if(r.kind==='development'){window.openDevelopmentBookmark(Number(r.key),r.tab);return;}if(r.kind==='motor'){window.openMotorBookmark(Number(r.key));return;}if(r.kind==='guide'){window.openMamaGuide(r.key);return;}if(r.kind==='section'&&sectionFns[r.key]){window[sectionFns[r.key]]();return;}}
const m=item.id.match(/^([a-z]+)-(\d+)$/);if(m&&typeof sections!=='undefined'&&Object.hasOwn(sections,m[1])){const n=Number(m[2]);if(m[1]==='development'&&n<12)window.openDevelopmentV2Age(n);else if(m[1]==='sleep'&&n===21)window.openSleepV2Analyzer();else if(n<sections[m[1]].items.length)window.openArticle(m[1],n);else{status('Материал изменился. Откроем его раздел.');window.openSection(m[1]);}return;}status('Эту старую закладку не удалось сопоставить с материалом. Название сохранено — найдите тему в разделе «Малыш» или «Мама».');}catch{status('Материал сейчас не удалось открыть. Закладка сохранена; попробуйте снова.');}}
function label(item){return groups[item.route?.kind]||groups.legacy;}
function cards(q=''){const box=root.querySelector('#fav-results');if(!box)return;const rows=read().filter(x=>(x.title+' '+label(x)).toLocaleLowerCase('ru').includes(q.toLocaleLowerCase('ru')));box.innerHTML=rows.map(x=>`<article class="fav-card"><button type="button" class="fav-open" data-fav-open="${esc(x.id)}"><small>${esc(label(x))}</small><strong>${esc(x.title)}</strong><span>Открыть →</span></button><button type="button" class="fav-remove" data-fav-remove="${esc(x.id)}" aria-label="Убрать из избранного: ${esc(x.title)}">Убрать</button></article>`).join('')||`<div class="mz-note">${q?'По этому запросу ничего не найдено. Попробуйте другое слово.':'Пока здесь пусто. Откройте памятку и нажмите «♡ Сохранить в избранное». Она появится здесь.'}</div>`;root.querySelector('#fav-count').textContent=`Сохранено: ${read().length}`;}
function render(){closeModal();root.innerHTML=`<div class="mz-today"><button class="mz-link" type="button" data-mz="more">← Ещё</button><span class="mz-eyebrow">ПОЛЕЗНОЕ ПОД РУКОЙ</span><h1 tabindex="-1">Избранное</h1><p>Ваши памятки и занятия. Нажмите на карточку, чтобы открыть материал.</p><label class="mz-label" for="fav-search">Найти в избранном</label><input id="fav-search" type="search" placeholder="Например, сон или купание"><p id="fav-count" class="mz-muted" role="status"></p><div id="fav-results"></div><div id="fav-undo" role="status"></div><p class="mz-footnote">Закладки хранятся в этом браузере. При очистке его данных они удалятся.</p></div>`;cards();root.querySelector('#fav-search').addEventListener('input',e=>cards(e.target.value.trim()));window.scrollTo(0,0);root.querySelector('h1').focus({preventScroll:true});}
window.MamaFavorites={offer};window.MamaFavoriteArticles=window.MamaFavoriteArticles||{};window.favorites=render;
window.toggleFavorite=(id,title)=>toggle({id:String(id),title:String(title)});
for(const [key,name]of Object.entries(sectionFns)){const original=window[name];if(typeof original!=='function')continue;window[name]=function(){const result=original.apply(this,arguments);const heading=root.querySelector('h1');if(heading)offer({kind:'section',key,title:heading.textContent.trim()});return result;};}
document.addEventListener('click',e=>{const b=e.target.closest('[data-fav-open],[data-fav-remove],[data-fav-undo]');if(!b)return;if(b.hasAttribute('data-fav-open')){const item=read().find(x=>x.id===b.dataset.favOpen);if(item)open(item);}else if(b.hasAttribute('data-fav-remove')){const rows=read(),item=rows.find(x=>x.id===b.dataset.favRemove);if(!item)return;if(!write(rows.filter(x=>x.id!==item.id))){status('Не удалось убрать закладку.');return;}removed=item;cards(root.querySelector('#fav-search').value);root.querySelector('#fav-undo').innerHTML='Закладка убрана. <button type="button" class="mz-link" data-fav-undo>Вернуть</button>';}else if(removed){const rows=read();if(!rows.some(x=>x.id===removed.id))rows.push(removed);if(!write(rows)){status('Не удалось вернуть закладку.');return;}removed=null;cards(root.querySelector('#fav-search').value);root.querySelector('#fav-undo').textContent='Закладка возвращена.';}});
})();
