/* Shared profile and personal plans. Medical schedules stay in their source modules. */
(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function parse(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s?d:null;}
function add(s,m){const d=parse(s);if(!d)return '';const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+Math.floor(m));d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));if(m%1)d.setUTCDate(d.getUTCDate()+15);return d.toISOString().slice(0,10);}
function months(s,n=today()){if(!parse(s)||!parse(n)||s>n)return null;const b=parse(s),d=parse(n);let m=(d.getUTCFullYear()-b.getUTCFullYear())*12+d.getUTCMonth()-b.getUTCMonth();return add(s,m)>n?m-1:m;}
function read(k,f={}){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v&&typeof v==='object'&&!Array.isArray(v)?v:f;}catch{return f;}}
function get(){return typeof baby==='object'&&baby?baby:read('baby');}
function birth(){const b=get().birth;return parse(b)&&b<=today()?b:'';}
function save(next){try{localStorage.setItem('baby',JSON.stringify(next));baby=next;return true;}catch{return false;}}
const fmt=s=>parse(s)?parse(s).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}):'Дата не указана';
function dateField(){return `<div class="mp-profile-link"><b>Дата рождения: ${birth()?fmt(birth()):'пока не указана'}</b><p>Одна дата для всех разделов.</p><button type="button" data-profile-open>Изменить профиль</button></div>`;}
function profile(){closeModal();const p=get();document.getElementById('screen').innerHTML=`<main class="mz-today mp-page"><button type="button" data-mz="today" class="mz-link">← Сегодня</button><span class="mz-eyebrow">НАСТРОИТЬ ОДИН РАЗ</span><h1 tabindex="-1">Мой малыш</h1><p>Возраст и даты в разделах будут считаться из этого профиля.</p><form id="mp-form"><label>Имя или домашнее прозвище<input name="name" maxlength="60" value="${esc(p.name||'')}" placeholder="Можно оставить пустым"></label><label>Дата рождения<input name="birth" type="date" max="${today()}" value="${esc(birth())}" required></label><label>Как кормите малыша<select name="feeding">${[['','Пока не указывать'],['breast','Грудное молоко'],['formula','Смесь'],['mixed','Грудное молоко и смесь']].map(([v,t])=>`<option value="${v}" ${p.feeding===v?'selected':''}>${t}</option>`).join('')}</select></label><details ${p.gestationWeeks?'open':''}><summary>Малыш родился раньше срока?</summary><p>Если знаете, укажите срок беременности при рождении из выписки. Поле необязательное.</p><label>Полных недель<input name="weeks" type="number" min="22" max="42" step="1" value="${p.gestationWeeks||''}"></label><label>Дополнительно дней<select name="days">${Array.from({length:7},(_,i)=>`<option ${p.gestationDays===i?'selected':''}>${i}</option>`).join('')}</select></label><p>Календари используют возраст от даты рождения. Для развития у недоношенного малыша подходящие ориентиры уточняйте с врачом; срок не переносит даты прививок автоматически.</p></details><p class="mz-note">При исправлении даты рождения отметки осмотров и личные планы останутся привязаны к прежней дате. Если вернуть её, записи снова появятся. Дневник сна и избранное сохранятся.</p><button type="submit" class="mz-primary">Сохранить профиль</button><p id="mp-status" role="alert"></p></form><p class="mz-footnote">Данные остаются в этом браузере. Это профиль одного малыша, не переключение между детьми.</p></main>`;const form=document.getElementById('mp-form');form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),b=f.get('birth'),w=f.get('weeks');if(!parse(b)||b>today()){document.getElementById('mp-status').textContent='Проверьте дату рождения.';return;}if(w!==''&&(!Number.isInteger(+w)||+w<22||+w>42))return;const next={...get(),name:f.get('name').trim()||'Малыш',birth:b,feeding:f.get('feeding'),gestationWeeks:w===''?null:+w,gestationDays:w===''?0:+f.get('days')};if(!save(next)){document.getElementById('mp-status').textContent='Не удалось сохранить. Старый профиль не изменён. Проверьте настройки браузера.';return;}window.openMamaToday();});window.scrollTo(0,0);document.querySelector('#screen h1').focus();}
const adapters={};
function records(){return read('mamaPlansV1');}
function record(id){return records()[birth()]?.[id]||{};}
function put(id,value){try{const raw=localStorage.getItem('mamaPlansV1'),all=raw?JSON.parse(raw):{};if(!all||typeof all!=='object'||Array.isArray(all)||!birth())return false;all[birth()]={...(all[birth()]||{}),[id]:value};localStorage.setItem('mamaPlansV1',JSON.stringify(all));return true;}catch{return false;}}
function tasks(){return Object.values(adapters).flatMap(fn=>fn()).map(t=>({...t,...record(t.id),done:t.done||record(t.id).done===true}));}
function controls(t){const r=record(t.id);return `<button type="button" class="mz-link" data-plan-edit="${esc(t.id)}">${r.done?'Сделано · изменить':r.planned?'Запланировано · изменить':'Запланировать / отметить'}</button>`;}
function edit(id){const t=tasks().find(t=>t.id===id);if(!t)return;const r=record(id);modalBody.innerHTML=`<div class="mp-page"><h2>${esc(t.title)}</h2><p>${esc(t.note||'Личная запись; она не назначает медицинскую процедуру.')}</p><form id="mp-plan-form"><label>Статус<select name="status"><option value="planned" ${!r.done?'selected':''}>Запланировано</option>${t.kind==='vaccine'?`<option value="done" ${r.done?'selected':''}>Сделано</option>`:''}</select></label><label>Дата приёма или выполненной прививки<input name="date" type="date" min="${birth()}" value="${esc(r.done?r.completed:r.planned||'')}" required></label><label>Показать карточку на главной с даты<input name="snooze" type="date" min="${today()}" value="${esc(r.snooze&&r.snooze>=today()?r.snooze:'')}"></label><p>«Напомнить позже» скрывает карточку до выбранной даты. Push-уведомления не отправляются. Для осмотра отмечайте пройденные пункты в его разделе.</p><button type="submit" class="mz-primary">Сохранить отметку</button><button type="button" id="mp-plan-clear" class="mz-link">Убрать личную отметку</button><p id="mp-plan-status" role="alert"></p></form></div>`;modal.classList.remove('hidden');document.getElementById('mp-plan-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=f.get('date'),s=f.get('snooze'),done=f.get('status')==='done';if(!parse(d)||d<birth()||done&&d>today()||s&&(!parse(s)||s<today())){document.getElementById('mp-plan-status').textContent='Проверьте даты: выполненное нельзя отметить будущим числом.';return;}if(!put(id,{done,completed:done?d:'',planned:done?'':d,snooze:done?'':s})){document.getElementById('mp-plan-status').textContent='Не удалось сохранить отметку.';return;}closeModal();window.openMamaToday();};document.getElementById('mp-plan-clear').onclick=()=>{if(put(id,{})){closeModal();window.openMamaToday();}else document.getElementById('mp-plan-status').textContent='Не удалось сохранить изменения.';};}
function upcoming(){if(!birth())return `<section class="mz-next"><h2>Ближайшее для малыша</h2><p>Укажите дату рождения один раз — покажем осмотры, возрастные ориентиры прививок и ваш план прикорма.</p><button type="button" data-profile-open>Заполнить профиль</button></section>`;const all=tasks(),now=today(),a=months(birth());const eligible=all.filter(t=>!t.done&&(!t.snooze||t.snooze<=now)&&(t.planned||t.kind==='feeding'||t.month>=a));eligible.sort((a,b)=>(a.planned||a.due).localeCompare(b.planned||b.due));const chosen=eligible.slice(0,4),hidden=all.filter(t=>!t.done&&t.snooze>now),old=all.some(t=>!t.done&&!t.planned&&t.kind==='vaccine'&&t.month<a);return `<section class="mz-next mp-upcoming"><span class="mz-eyebrow">ВАШ ПЛАН</span><h2>Ближайшее</h2><p>Возрастные даты — ориентиры. Личную дату приёма добавляйте после согласования с врачом.</p>${chosen.map(t=>`<article class="mp-task"><small>${t.kind==='exam'?'ОСМОТР':t.kind==='vaccine'?'ПРИВИВКА':'ПРИКОРМ'} · ${t.planned?'Запланировано':'Ориентир'}</small><h3>${esc(t.title)}</h3><p>${fmt(t.planned||t.due)}${t.planned&&t.planned<now?' · дата прошла, проверьте отметку':''}</p><p>${esc(t.note||'')}</p><button type="button" class="mz-secondary" data-task-open="${esc(t.id)}">${t.kind==='exam'?'Открыть список и отметить пройденное':'Открыть раздел'}</button>${t.kind!=='feeding'?controls(t):''}</article>`).join('')||'<p>Ближайших карточек пока нет. Календари и ваши записи доступны ниже.</p>'}${old?'<p class="mz-note">Есть прививки прошлых возрастов без отметок. Это не означает, что они пропущены: сверьте календарь с сертификатом. Догоняющую схему составляет врач.</p>':''}${hidden.length?`<details><summary>Напомнить позже · ${hidden.length}</summary>${hidden.map(t=>`<p>${esc(t.title)} — покажем ${fmt(t.snooze)}</p>${controls(t)}`).join('')}</details>`:''}<button type="button" data-mz="exams" class="mz-link">Все осмотры</button><button type="button" data-mz="vaccines" class="mz-link">Все прививки и отметки</button></section>`;}
window.MamaProfile={get,birth,save,months,add,today,parse,fmt,dateField};window.MamaPlans={adapters,record,controls,upcoming,tasks};window.profile=profile;
document.addEventListener('click',e=>{const b=e.target.closest('[data-profile-open],[data-plan-edit],[data-task-open]');if(!b)return;if(b.hasAttribute('data-profile-open'))profile();else if(b.dataset.planEdit)edit(b.dataset.planEdit);else tasks().find(t=>t.id===b.dataset.taskOpen)?.open();});
})();
