/* First-minute experience. Reuses the existing guides and child profile. */
(function () {
'use strict';
const root = document.getElementById('screen');
const KEY = 'mamaTodayV1';
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
const raw = read(KEY, {});
let settings = raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {};
let demo = false, page = 'today', draft = null;
const topics = [
 ['sleep','☾','Разобраться со сном','Короткие сны, пробуждения и укладывание'],
 ['feeding','◡','Наладить кормление','Грудное молоко, смесь и сигналы малыша'],
 ['development','✿','Играть и развиваться','Что интересно малышу прямо сейчас'],
 ['complementary','◒','Начать или продолжить прикорм','План с учётом вашего темпа'],
 ['mother','♡','Позаботиться о себе','Восстановление и грудное вскармливание']
];
const catalog = [
 ['development','Развитие','Умения, зрение, слух и игры','навыки видит слышит игрушки'],
 ['motor','Зарядка и упражнения','По навыкам, с видео','голова переворот ползание сидение ходьба опора'],
 ['sleep','Сон','Разобрать ситуацию и вести наблюдения','ночь просыпается укладывание короткий сон'],
 ['feeding','Кормление','Грудное молоко, смесь, бутылочка','еда соска голод ив гв'],
 ['complementary','Прикорм','Продукты, порции и ваш календарь','овощ ложка аллергены еда'],
 ['vaccines','Прививки в России','Плановые и дополнительные','вакцина календарь'],
 ['exams','Профилактические осмотры','Врачи, обследования и подготовка','педиатр анализы врач'],
 ['growth','Календарь роста и сна','Недели жизни и ориентиры','скачки регресс'],
 ['care','Уход за малышом','Понятные инструкции на каждый день','купание подгузник ногти'],
 ['health','Здоровье','Частые вопросы и когда нужна помощь','температура сыпь стул'],
 ['postpartum','После естественных родов','Восстановление мамы шаг за шагом','мама роды'],
 ['cesarean','После кесарева сечения','Восстановление и повседневные дела','кс шов мама'],
 ['breastfeeding','Грудное вскармливание','Прикладывание, сцеживание, сложности','гв грудь лактостаз мастит накладки']
];
function todayDate() { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12); }
function iso(d) { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function parseDate(s) { if(!/^\d{4}-\d{2}-\d{2}$/.test(s || '')) return null; const d = new Date(s+'T12:00:00'); return Number.isFinite(+d) && iso(d)===s ? d : null; }
function monthsBetween(b,n=todayDate()) { return (n.getFullYear()-b.getFullYear())*12+n.getMonth()-b.getMonth()-(n.getDate()<b.getDate()?1:0); }
function birth() { const d = parseDate(typeof baby !== 'undefined' ? baby?.birth : ''); return d && d<=todayDate() ? d : null; }
function age() { if(demo) return 4; const b=birth(); if(b) return monthsBetween(b); const d=parseDate(settings.ageOn); return Number.isInteger(settings.month) && settings.month>=0 && d ? settings.month+Math.max(0,monthsBetween(d)) : null; }
function ageText(n) { return n===null?'Возраст пока не указан':`${n} ${n%100>=11&&n%100<=14?'месяцев':n%10===1?'месяц':n%10>=2&&n%10<=4?'месяца':'месяцев'}`; }
function topic() { return topics.find(t=>t[0]===settings.topic)?.[0] || 'development'; }
function show(html, active=page) { closeModal(); page=active; root.innerHTML=`<div class="mz-today">${html}</div>`; nav(active); window.scrollTo(0,0); root.querySelector('h1')?.focus({preventScroll:true}); }
function nav(active) { document.querySelectorAll('#mz-nav button').forEach(b=>{if(b.dataset.mz===active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}); }
const button=(action,text,cls='mz-primary')=>`<button type="button" class="${cls}" data-mz="${action}">${text}</button>`;
const back=()=>button('today','← Сегодня','mz-link');
function welcome() { show(`<section class="mz-welcome"><span class="mz-eyebrow">ВАШ ПЕРВЫЙ ГОД ВМЕСТЕ</span><div class="mz-flower" aria-hidden="true">✿</div><h1 tabindex="-1">Чуть больше ясности.<br>Чуть спокойнее день.</h1><p class="mz-lead">Понятно, что делать сегодня — для малыша и для себя.</p><p>Сон, кормление, игры и восстановление. Подберём начало по возрасту и вашему вопросу.</p>${button('setup','Подобрать для нас <span aria-hidden="true">→</span>')}${button('demo','Посмотреть пример для 4 месяцев','mz-secondary')}<small>Два коротких шага. Дату рождения можно добавить позже.</small></section><div class="mz-promise"><span>01</span><p><strong>Всё по шагам</strong>Сначала — что сделать. Подробности — когда они нужны.</p></div><div class="mz-promise"><span>02</span><p><strong>В вашем темпе</strong>Можно начать с одного вопроса и вернуться к остальному позже.</p></div>${button('baby','Просто посмотреть разделы','mz-link')}`, 'today'); }
function startSetup() { demo=false; draft={month:age()===null?'':String(Math.min(12,age())),birth:birth()?iso(birth()):'',topic:topic(),mode:birth()?'date':'age'}; setupAge(); }
function setupAge() { show(`${back()}<span class="mz-eyebrow">ШАГ 1 ИЗ 2</span><h1 tabindex="-1">Сколько малышу?</h1><p>Покажем подходящие игры и материалы. Точную дату можно указать позже.</p><form id="mz-age-form"><div class="mz-switch"><label><input type="radio" name="ageMode" value="age" ${draft.mode==='age'?'checked':''}> Укажу возраст</label><label><input type="radio" name="ageMode" value="date" ${draft.mode==='date'?'checked':''}> Дата рождения</label></div><div id="mz-age-wrap" ${draft.mode==='date'?'hidden':''}><label class="mz-label" for="mz-month">Полных месяцев</label><select id="mz-month"><option value="">Выберите возраст</option>${Array.from({length:13},(_,i)=>`<option value="${i}" ${String(i)===draft.month?'selected':''}>${i===0?'Меньше месяца':ageText(i)}</option>`).join('')}</select><p class="mz-muted">При приблизительном возрасте календарные даты не рассчитываются.</p></div><div id="mz-date-wrap" ${draft.mode==='age'?'hidden':''}><label class="mz-label" for="mz-birth">Дата рождения малыша</label><input id="mz-birth" type="date" max="${iso(todayDate())}" value="${esc(draft.birth)}"><p class="mz-muted">Используем её в профиле и календарях.</p></div><p class="mz-error" id="mz-error" role="alert"></p><button class="mz-primary" type="submit">Дальше →</button></form>`, 'today'); }
function setupTopic() { show(`${button('age-step','← Возраст','mz-link')}<span class="mz-eyebrow">ШАГ 2 ИЗ 2</span><h1 tabindex="-1">Что сейчас важнее?</h1><p>Начнём с одной темы. Все остальные разделы тоже будут доступны.</p><form id="mz-topic-form"><div class="mz-topics">${topics.map(([id,icon,title,desc])=>`<label class="mz-choice"><input type="radio" name="topic" value="${id}" ${draft.topic===id?'checked':''}><span class="mz-choice-icon" aria-hidden="true">${icon}</span><span><strong>${title}</strong><small>${desc}</small></span></label>`).join('')}</div><p class="mz-error" id="mz-error" role="alert"></p><button class="mz-primary" type="submit">Показать мою подборку →</button><p class="mz-muted">Настройки сохранятся в этом браузере. Их можно изменить в любой момент.</p></form>`, 'today'); }
function commitSetup() { const chosen=root.querySelector('input[name="topic"]:checked'); if(!chosen)return; const next={...settings,topic:chosen.value,month:draft.mode==='age'?Number(draft.month):null,ageOn:iso(todayDate()),done:true}; const nextBaby={...(typeof baby==='object'&&baby?baby:{}),birth:draft.mode==='date'?draft.birth:'',name:typeof baby==='object'&&baby?.name?baby.name:'Малыш'}; const oldProfile=localStorage.getItem('baby'); try {localStorage.setItem('baby',JSON.stringify(nextBaby)); localStorage.setItem(KEY,JSON.stringify(next));} catch {try{if(oldProfile===null)localStorage.removeItem('baby');else localStorage.setItem('baby',oldProfile);}catch{} root.querySelector('#mz-error').textContent='Не удалось сохранить настройки. Проверьте, разрешено ли хранение данных в браузере, и попробуйте ещё раз.'; return;} baby=nextBaby; settings=next; draft=null; home(); }
function selectedGame() {const n=age(); if(n===null || n>11 || typeof MAMA_DEV4==='undefined')return null; const m=MAMA_DEV4.months[n]; const day=Math.floor(Date.UTC(new Date().getFullYear(),new Date().getMonth(),new Date().getDate())/86400000); return MAMA_DEV4.games[m.games[day%m.games.length]]; }
function primaryCard() { const id=topic(), n=age(); const content={sleep:['Начнём с вашего вопроса','Выберите, что происходит со сном. Внутри — понятная памятка и действия по порядку.','sleep-quick','Разобраться со сном'],feeding:['Кормление без лишней путаницы','Откройте свой способ кормления: грудное молоко, смесь или сочетание.','feeding','Выбрать способ кормления'],development:['Посмотрите на мир глазами малыша',n!==null&&n<12?'Умения, зрение, слух и игры для вашего возраста.':'Выберите возраст в разделе: умения, зрение, слух и игры.','development','Открыть развитие'],complementary:['Прикорм в вашем темпе','Укажите знакомые продукты и темп введения. Календарь подстроится под настройки.','complementary','Открыть прикорм'],mother:['Здесь есть место и для вас','Выберите восстановление после родов или помощь с грудным вскармливанием.','mother','Посмотреть для себя']}[id]; return `<section class="mz-focus"><span class="mz-eyebrow">С ЧЕГО НАЧНЁМ</span><h2>${content[0]}</h2><p>${content[1]}</p>${button(content[2],content[3]+' →')}</section>`; }
function home() { if(!demo&&!settings.done&&!birth())return welcome(); const n=age(), g=selectedGame(), title=demo?'Так может выглядеть ваш день': 'Сегодня для вас'; show(`${demo?'<div class="mz-demo">Пример для малыша 4 месяцев. Данные вашего ребёнка не меняются.'+button('setup','Настроить для нас','mz-link')+'</div>':''}<div class="mz-heading"><span class="mz-eyebrow">МАМА ЗНАЕТ · РЯДОМ КАЖДЫЙ ДЕНЬ</span><h1 tabindex="-1">${title}</h1><div class="mz-age"><span>${demo?'Пример · ':!birth()?'Примерно · ':''}${ageText(n)}</span>${button('setup','Изменить','mz-link')}</div></div>${n>11?'<p class="mz-note">Малышу уже год или больше. Здесь собраны материалы о первом годе; они остаются доступны в библиотеке.</p>':''}${primaryCard()}${g?`<section class="mz-game"><span class="mz-eyebrow">ПОПРОБУЙТЕ ВМЕСТЕ</span><h2>${esc(g.title)}</h2><p>${esc(g.about)}.</p>${button('game','Как поиграть →','mz-secondary')}<small>По настроению малыша. Это предложение, а не обязательное задание.</small></section>`:''}<section class="mz-next"><span class="mz-eyebrow">ВАЖНОЕ ПОД РУКОЙ</span><h2>Ближайшие дела</h2><p>${birth()&&!demo?'Осмотры учитывают дату рождения и ваши отметки. Даты прививок уточняйте с педиатром.':'Укажите дату рождения в календарях, чтобы увидеть даты для малыша.'}</p>${row('exams','Профилактический осмотр','Врачи и подготовка')}${row('vaccines','Прививки в России','Плановые и дополнительные')}</section>${button('baby','Все разделы для малыша →','mz-secondary')}<p class="mz-footnote">Информация справочная и не заменяет консультацию врача.</p>`, 'today'); }
function row(id,title,desc) {return `<button type="button" class="mz-row" data-mz="${id}"><span><strong>${title}</strong><small>${desc}</small></span><span aria-hidden="true">↗</span></button>`;}
function library(group='baby') {let entries=group==='mother'?catalog.slice(10):catalog.slice(0,10);show(`<span class="mz-eyebrow">${group==='mother'?'ЗАБОТА О ВАС':'БИБЛИОТЕКА ПЕРВОГО ГОДА'}</span><h1 tabindex="-1">${group==='mother'?'Для мамы':'Для малыша'}</h1><p>${group==='mother'?'Понятные шаги для восстановления и грудного вскармливания.':'Выберите тему или найдите её по знакомым словам.'}</p><label class="mz-label" for="mz-search">Найти раздел</label><input id="mz-search" type="search" placeholder="Например, сон или переворот" autocomplete="off"><div id="mz-results">${entries.map(x=>row(x[0],x[1],x[2])).join('')}</div><p id="mz-search-status" class="mz-muted" role="status"></p>`, group); }
function game() {const g=selectedGame();if(!g)return route('development');show(`${back()}<span class="mz-eyebrow">ИГРА ПО ВОЗРАСТУ · ${ageText(age())}</span><h1 tabindex="-1">${esc(g.title)}</h1><p class="mz-lead">${esc(g.about)}</p><section class="mz-white"><h2>Что понадобится</h2><p>${esc(g.need)}</p><h2>Как играть</h2><ol class="mz-steps">${g.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h2>Если пока трудно</h2><p>${esc(g.easier)}</p><p class="mz-note"><strong>Безопасность.</strong> ${esc(g.safe)}</p><details><summary>Что можно заметить</summary><p>${esc(g.notice)}</p></details></section>${button('development','Ещё игры и развитие →','mz-secondary')}`, 'today'); }
function sleepQuick() {show(`${back()}<span class="mz-eyebrow">ОДИН ВОПРОС ЗА РАЗ</span><h1 tabindex="-1">Что происходит со сном?</h1><p>Откройте подходящую ситуацию. Для чтения памятки не нужно заполнять дневник.</p><div class="mz-white">${[['sleep-short','Сны по 20–40 минут'],['sleep-early','Рано просыпается утром'],['sleep-wakes','Регресс и новые пробуждения'],['sleep-transfer','Просыпается при перекладывании'],['sleep-routine','Режим и переходы между снами']].map(([id,t])=>`<button class="mz-row" type="button" data-sd-guide="${id}"><strong>${t}</strong><span aria-hidden="true">↗</span></button>`).join('')}</div><section class="mz-game"><h2>Хочу увидеть картину дня</h2><p>Подробный анализатор учитывает дневные сны, ночное бодрствование и полноту записей.</p>${button('analyzer','Записать и разобрать день →','mz-secondary')}</section>${button('sleep','Все материалы о сне','mz-link')}`, 'baby'); }
function more() {show(`<span class="mz-eyebrow">ВАШЕ ПРОСТРАНСТВО</span><h1 tabindex="-1">Настройки и сохранённое</h1>${row('setup','Моя подборка','Изменить возраст и главную тему')}${row('profile','Профиль малыша','Имя и точная дата рождения')}${row('favorites','Избранное','Сохранённые материалы')}<p class="mz-note">Настройки и записи пока хранятся в этом браузере. При очистке его данных они удалятся.</p>`, 'more'); }
function route(id) { const action={today:()=>home(),baby:()=>library(),mother:()=>library('mother'),more,setup:startSetup,'age-step':setupAge,demo:()=>{demo=true;home();},game,'sleep-quick':sleepQuick,development:()=>{const n=age();if(n!==null&&n<12)window.openDevelopmentV2Age(n);else window.openDevelopmentV2();},motor:()=>window.openMotorExercises(),growth:()=>window.openGrowthCalendar(),vaccines:()=>window.openVaccinationCalendar(),exams:()=>window.openPreventiveExams(),analyzer:()=>window.openSleepV2Analyzer(),diary:()=>window.diary(),favorites:()=>window.favorites(),profile:()=>window.profile()}; if(action[id])action[id]();else if(catalog.some(x=>x[0]===id))window.openSection(id); if(!['today','baby','mother','more','setup','age-step','demo','game','sleep-quick'].includes(id))nav(id==='diary'?'diary':['postpartum','cesarean','breastfeeding'].includes(id)?'mother':id==='profile'||id==='favorites'?'more':'baby'); }
const navigation=document.createElement('nav'); navigation.id='mz-nav';navigation.className='mz-nav';navigation.setAttribute('aria-label','Основная навигация');navigation.innerHTML=[['today','⌂','Сегодня'],['baby','✿','Малыш'],['mother','♡','Мама'],['diary','▤','Дневник'],['more','•••','Ещё']].map(([id,icon,label])=>`<button type="button" data-mz="${id}"><span aria-hidden="true">${icon}</span>${label}</button>`).join('');document.getElementById('app').append(navigation);
document.addEventListener('click', e=>{const b=e.target.closest('[data-mz]');if(b)route(b.dataset.mz);});
root.addEventListener('change', e=>{if(e.target.name==='ageMode'){draft.mode=e.target.value;root.querySelector('#mz-age-wrap').hidden=draft.mode==='date';root.querySelector('#mz-date-wrap').hidden=draft.mode==='age';}});
root.addEventListener('submit', e=>{if(e.target.id==='mz-age-form'){e.preventDefault();draft.month=root.querySelector('#mz-month').value;draft.birth=root.querySelector('#mz-birth').value;const b=parseDate(draft.birth);if((draft.mode==='age'&&draft.month==='')||(draft.mode==='date'&&(!b||b>todayDate()))){root.querySelector('#mz-error').textContent='Выберите возраст или укажите корректную дату рождения не позже сегодняшнего дня.';return;}setupTopic();}else if(e.target.id==='mz-topic-form'){e.preventDefault();commitSetup();}});
root.addEventListener('input',e=>{if(e.target.id!=='mz-search')return;const q=e.target.value.trim().toLocaleLowerCase('ru').replace(/ё/g,'е');const entries=(page==='mother'?catalog.slice(10):catalog.slice(0,10)).filter(x=>x.join(' ').toLocaleLowerCase('ru').replace(/ё/g,'е').includes(q));root.querySelector('#mz-results').innerHTML=entries.map(x=>row(x[0],x[1],x[2])).join('');root.querySelector('#mz-search-status').textContent=entries.length?'':'Такой раздел не найден. Попробуйте «сон», «кормление» или «уход».';});
// Keep the existing profile dialog; refresh Today after saving it.
const oldSave=window.saveProfile;window.saveProfile=function(){const val=document.getElementById('babyBirth')?.value;const d=parseDate(val);if(val&&(!d||d>todayDate())){let error=document.getElementById('mz-profile-error');if(!error){error=document.createElement('p');error.id='mz-profile-error';error.setAttribute('role','alert');modalBody.append(error);}error.textContent='Дата рождения не может быть позже сегодняшнего дня.';return;}oldSave();if(page==='today')home();};
window.openMamaToday=()=>{demo=false;home();};
home();
})();
